# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadfile1 = QtWidgets.QPushButton(self.centralwidget)
        self.loadfile1.setObjectName("loadfile1")
        self.horizontalLayout.addWidget(self.loadfile1)
        self.loadfile2 = QtWidgets.QPushButton(self.centralwidget)
        self.loadfile2.setObjectName("loadfile2")
        self.horizontalLayout.addWidget(self.loadfile2)
        self.loadfile3 = QtWidgets.QPushButton(self.centralwidget)
        self.loadfile3.setObjectName("loadfile3")
        self.horizontalLayout.addWidget(self.loadfile3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.sepearation = QtWidgets.QPushButton(self.centralwidget)
        self.sepearation.setObjectName("sepearation")
        self.gridLayout.addWidget(self.sepearation, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.playsound1 = QtWidgets.QPushButton(self.centralwidget)
        self.playsound1.setObjectName("playsound1")
        self.horizontalLayout_2.addWidget(self.playsound1)
        self.playsound2 = QtWidgets.QPushButton(self.centralwidget)
        self.playsound2.setObjectName("playsound2")
        self.horizontalLayout_2.addWidget(self.playsound2)
        self.playsound3 = QtWidgets.QPushButton(self.centralwidget)
        self.playsound3.setObjectName("playsound3")
        self.horizontalLayout_2.addWidget(self.playsound3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.save1 = QtWidgets.QPushButton(self.centralwidget)
        self.save1.setObjectName("save1")
        self.horizontalLayout_3.addWidget(self.save1)
        self.save2 = QtWidgets.QPushButton(self.centralwidget)
        self.save2.setObjectName("save2")
        self.horizontalLayout_3.addWidget(self.save2)
        self.save3 = QtWidgets.QPushButton(self.centralwidget)
        self.save3.setObjectName("save3")
        self.horizontalLayout_3.addWidget(self.save3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_4.addWidget(self.graphicsView)
        self.graphicsView_4 = PlotWidget(self.centralwidget)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.horizontalLayout_4.addWidget(self.graphicsView_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 4, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.graphicsView_2 = PlotWidget(self.centralwidget)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.horizontalLayout_6.addWidget(self.graphicsView_2)
        self.graphicsView_5 = PlotWidget(self.centralwidget)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.horizontalLayout_6.addWidget(self.graphicsView_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout_2, 5, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.graphicsView_3 = PlotWidget(self.centralwidget)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.horizontalLayout_8.addWidget(self.graphicsView_3)
        self.graphicsView_6 = PlotWidget(self.centralwidget)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.horizontalLayout_8.addWidget(self.graphicsView_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.verticalLayout_3, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadfile1.setText(_translate("MainWindow", "load_mix 1"))
        self.loadfile2.setText(_translate("MainWindow", "load mix 2"))
        self.loadfile3.setText(_translate("MainWindow", "load mix 3"))
        self.sepearation.setText(_translate("MainWindow", "seperation"))
        self.playsound1.setText(_translate("MainWindow", "play sound1"))
        self.playsound2.setText(_translate("MainWindow", "play sound 2"))
        self.playsound3.setText(_translate("MainWindow", "play sound 3"))
        self.save1.setText(_translate("MainWindow", "save 1"))
        self.save2.setText(_translate("MainWindow", "save 2"))
        self.save3.setText(_translate("MainWindow", "save 3"))
        self.label.setText(_translate("MainWindow", "mix1 "))
        self.label_2.setText(_translate("MainWindow", "result1"))
        self.label_3.setText(_translate("MainWindow", "mix2"))
        self.label_4.setText(_translate("MainWindow", "result2"))
        self.label_5.setText(_translate("MainWindow", "mix3"))
        self.label_6.setText(_translate("MainWindow", "result3"))

from pyqtgraph import PlotWidget
